config/routes.rb
Rails.application.routes.draw do
	root 'root#index'

	resources :networks do
		resources :devices, only: [:index, :new, :create], name_prefix: 'network_'
	end

	resources :devices do
		resources :networks, only: [:index, :new, :create], name_prefix: 'device_'
	end
end

app/models/device.rb
class Device < ActiveRecord::Base
	has_many :probes
	has_many :networks, -> { uniq }, through: :probes

	validates :mac, presence: true, uniqueness: true
end

app/models/network.rb
class Network < ActiveRecord::Base
	has_many :probes
	has_many :devices, -> { uniq }, through: :probes

	validates :name, presence: true, uniqueness: true
end

app/models/probe.rb
class Probe < ActiveRecord::Base
	belongs_to :device
	belongs_to :network
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
	before_action :set_parent, only: [:index, :new, :create]
	before_action :set_device, only: [:show, :edit, :update, :destroy]

	def index
		if @network
			@devices = @network.devices
		else
			@devices = Device.all
		end
	end

	def show
	end

	def new
		@device = Device.new
	end

	def edit
	end

	def create
		@device = Device.new device_params

		respond_to do |format|
			if @device.save
				format.html { redirect_to @device, notice: 'Device was successfully created.' }
				format.json { render :show, status: :created, location: @device }
			else
				format.html { render :new }
				format.json { render json: @device.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @device.update device_params
				format.html { redirect_to @device, notice: 'Device was successfully updated.' }
				format.json { render :show, status: :ok, location: @device }
			else
				format.html { render :edit }
				format.json { render json: @device.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@device.destroy

		respond_to do |format|
			format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def self.get_obj(id)
		regex = /\Amac-([0-9A-F]{12})\Z/i
		mac = regex.match id

		if mac
			mac = mac[1]
			device = Device.find_by_mac mac

			unless device
				device = Device.create mac: mac
			end
		end

		device = Device.find id unless device

		device
	end

	private
		def set_device
			@device = self.class.get_obj params[:id]
		end

		def set_parent
			if params[:network_id]
				@network = NetworksController.get_obj params[:network_id]
			end
		end

		def device_params
			params.require(:device).permit(:mac)
		end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
	before_action :set_parent, only: [:index, :new, :create]
	before_action :set_network, only: [:show, :edit, :update, :destroy]

	def index
		if @device
			@networks = @device.networks
		else
			@networks = Network.all
		end
	end

	def show
	end

	def new
		@network = Network.new
	end

	def edit
	end

	def create
		if @device
			@network = Network.find_by_name network_params[:name]

			unless @network
				@network = Network.create network_params
			end

			Probe.create network: @network, device: @device, location: params[:location]
		end

		unless @network
			@network = Network.new network_params
		end

		respond_to do |format|
			if @network.save
				format.html { redirect_to @network, notice: 'Network was successfully created.' }
				format.json { render :show, status: :created, location: @network }
			else
				format.html { render :new }
				format.json { render json: @network.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @network.update network_params
				format.html { redirect_to @network, notice: 'Network was successfully updated.' }
				format.json { render :show, status: :ok, location: @network }
			else
				format.html { render :edit }
				format.json { render json: @network.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@network.destroy

		respond_to do |format|
			format.html { redirect_to networks_url, notice: 'Network was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def self.get_obj(id)
		Network.find id
	end

	private
		def set_network
			@network = self.class.get_obj params[:id]
		end

		def set_parent
			if params[:device_id]
				@device = DevicesController.get_obj params[:device_id]
			end
		end

		def network_params
			params.require(:network).permit(:name)
		end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_mac(mac)
		mac.scan(/.{2}/).join(':')
	end

	def bootstrap_class_for(flash_type)
		case flash_type
			when 'success'
				'alert-success'
			when 'error'
				'alert-error'
			when 'alert'
				'alert-block'
			when 'notice'
				'alert-info'
			else
				flash_type.to_s
		end
	end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/devices/_form.html.erb
<%= form_for([@network, @device]) do |f| %>
	<% if @device.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<p><%= pluralize @device.errors.count, 'error' %> prohibited this device from being saved:</p>

			<ul>
				<% @device.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :mac, 'MAC' %>
		<%= f.text_field :mac, class: 'form-control' %>
	</div>

	<%= f.submit class: 'btn btn-primary' %>
	<%= link_to 'Cancel', @device, class: 'btn btn-link' %>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

app/views/devices/index.html.erb
<h1>
	Listing devices

	<% if @network %>
		for <%= @network.name %>
	<% end %>
</h1>

<table class="table js-tablesorter">
	<thead>
		<tr>
			<th>MAC</th>
			<th>Networks</th>
			<th colspan="2"></th>
		</tr>
	</thead>

	<tbody>
		<% @devices.each do |device| %>
			<tr>
				<td><%= link_to render_mac(device.mac), device %></td>
				<td><%= link_to device.networks.count, device_networks_path(device) %></td>
				<td><%= link_to 'Edit', edit_device_path(device) %></td>
				<td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<% if @network %>
	<%= link_to 'New Device', new_network_device_path(@network), class: 'btn btn-default' %>
<% else %>
	<%= link_to 'New Device', new_device_path, class: 'btn btn-default' %>
<% end %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

app/views/devices/show.html.erb
<p>
	<strong>MAC:</strong>
	<%= render_mac(@device.mac) %>
</p>

<%= link_to 'Edit', edit_device_path(@device), class: 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8" />

		<title>Wi-Fi Privacy</title>

		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<%= csrf_meta_tags %>

		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

		<!--[if lt IE 9]>
			<script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		<div class="navbar navbar-default navbar-static-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="navbar-brand" href="/">Wi-Fi Privacy</a>
				</div>

				<nav class="collapse navbar-collapse" id="navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href="/devices">Devices</a></li>
						<li><a href="/networks">Networks</a></li>
					</ul>
				</nav>
			</div>
		</div>

		<div class="container">
			<% flash.each do |type, message| %>
				<div class="alert <%= bootstrap_class_for(type) %>">
					<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<%= message %>
				</div>
			<% end %>

			<%= yield %>
		</div>

		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	</body>
</html>

app/views/networks/_form.html.erb
<%= form_for([@device, @network]) do |f| %>
	<% if @network.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<p><%= pluralize @network.errors.count, 'error' %> prohibited this network from being saved:</p>

			<ul>
				<% @network.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<%= f.submit class: 'btn btn-primary' %>
	<%= link_to 'Cancel', @network, class: 'btn btn-link' %>
<% end %>

app/views/networks/edit.html.erb
<h1>Editing network</h1>

<%= render 'form' %>

app/views/networks/index.html.erb
<h1>
	Listing networks

	<% if @device %>
		for <%= render_mac(@device.mac) %>
	<% end %>
</h1>

<table class="table js-tablesorter">
	<thead>
		<tr>
			<th>Name</th>
			<th>Devices</th>
			<th colspan="2"></th>
		</tr>
	</thead>

	<tbody>
		<% @networks.each do |network| %>
			<tr>
				<td><%= link_to network.name, network %></td>
				<td><%= link_to network.devices.count, network_devices_path(network) %></td>
				<td><%= link_to 'Edit', edit_network_path(network) %></td>
				<td><%= link_to 'Destroy', network, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<% if @device %>
	<%= link_to 'New Network', new_device_network_path(@device), class: 'btn btn-default' %>
<% else %>
	<%= link_to 'New Network', new_network_path, class: 'btn btn-default' %>
<% end %>

app/views/networks/new.html.erb
<h1>New network</h1>

<%= render 'form' %>

app/views/networks/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @network.name %>
</p>

<%= link_to 'Edit', edit_network_path(@network), class: 'btn btn-default' %>

app/views/root/index.html.erb
<h1>Wi-Fi Privacy</h1>